# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: SSAFY diary
    output: web, pdf
    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
      output: web

    - title: SSAFY 1st Month
      url: /SSAFY_Jan.md
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.md
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.md
      output: web, pdf

  - title: Another heading
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.md
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.md
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.md
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.md
      output: web, pdf

# Copyright 2021 Google LLC
